export default {
    AF: 'Kabul',
    AX: 'Mariehamn',
    AL: 'Tirana',
    DZ: 'Algiers',
    AS: 'American Samoa', //not edited
    AD: 'Andorra la Vella',
    AO: 'Luanda',
    AI: 'Anguilla',// not edited
    AQ: 'Antarctica', // not edit
    AG: "St John's",
    AR: 'Buenos Aires',
    AM: 'Yerevan',
    AW: 'Oranjestad',
    AU: 'Sydney',
    AT: 'Vienna',
    AZ: 'Baku',
    BS: 'Nassau',
    BH: 'Manama',
    BD: 'Dhaka',
    BB: 'Bridgetown',
    BY: 'Minsk',
    BE: 'Brussels',
    BZ: 'Belmopan',
    BJ: 'Benin', //not edited
    BM: 'Hamilton',
    BT: 'Thimphu',
    BO: 'La Paz',
    BA: 'Sarajevo',
    BW: 'Gaborone',
    BR: 'Brasilia',
    IO: 'British Indian Ocean Territory', // not edited
    VG: 'Road Town',
    BN: 'Bandar Seri Begawan',
    BG: 'Sofia',
    BF: 'Ouagadougou',
    BI: 'Gitega',
    KH: 'Phnom Penh',
    CM: 'Yaounde',
    CA: 'Calgary',
    CV: 'Praia',
    BQ: 'Caribbean Netherlands', // not edited
    KY: 'George Town',
    CF: 'Central African Republic', //not edited
    TD: 'Baibokoum',
    CL: 'Santiago',
    CN: 'Beijing',
    CX: 'Christmas Island', //no edit
    CC: 'Cocos Islands', //no edit
    CO: 'Bogota',
    KM: 'Comoros', //no edit
    CG: 'Kinshasa',
    CK: 'Cook Islands', // no edit
    CR: 'San José',
    HR: 'Zagreb',
    CU: 'Havana',
    CW: 'Willemstad',
    CY: 'Nicosia',
    CZ: 'Prague',
    CD: 'Democratic Republic of the Congo', // no edit
    DK: 'Copenhagen',
    DJ: 'Djibouti',
    DM: 'Roseau',
    DO: 'Boca Chica',
    EC: 'Quito',
    EG: 'Cairo',
    SV: 'San Salvador',
    GQ: 'Malabo',
    ER: 'Eritrea', // no edit
    EE: 'Haapsalu',
    ET: 'Addis Ababa',
    FK: 'Falkland Islands', // no edit
    FO: 'Tórshavn',
    FM: 'Federated States of Micronesia', // no edit
    FJ: 'Fiji',
    FI: 'Helsinki',
    FR: 'Paris',
    GF: 'French Guiana', // no edit
    PF: 'Amaru',
    TF: 'French Southern Territories', // no edit
    GA: 'Libreville',
    GM: 'Banjul',
    GE: 'Tbilisi',
    DE: 'Berlin',
    GH: 'Tongo',
    GI: 'Gibraltar',
    GR: 'Athens',
    GL: 'Nuuk',
    GD: 'Sauteurs',
    GP: 'Guadeloupe',
    GU: 'Hagåtña',
    GT: 'Zacapa',
    GN: 'Guinea', // no edit
    GW: 'Gabu',
    GY: 'Georgetown',
    HT: 'Yoro',
    HN: 'La Paz',
    HK: 'Hong Kong',
    HU: 'Budapest',
    IS: 'Reykjavík',
    IN: 'Goa',
    ID: 'Ubud',
    IR: 'Tehran',
    IQ: 'Nasiriyah',
    IE: 'Dublin',
    IM: 'Ramsey',
    IL: 'Jerusalem',
    IT: 'Rome',
    CI: 'San-Pedro',
    JM: 'Kingston',
    JP: 'Tokyo',
    JE: 'St Helier',
    JO: 'Al-qasr',
    KZ: 'Shymkent',
    KE: 'Nairobi',
    KI: 'Kiribati', // no edit
    XK: 'Gjilan',
    KW: 'Rawda',
    KG: 'Kant',
    LA: 'Vientiane',
    LV: 'Jelgava',
    LB: 'Beirut',
    LS: 'Mafeteng',
    LR: 'Ganta',
    LY: 'Benghazi',
    LI: 'Liechtenstein', // no edit
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MO: 'Macao',
    MK: 'Macedonia', // no edit
    MG: 'Antananarivo',
    MW: 'Blantyre',
    MY: 'Kuala Lumpur',
    MV: 'Hulhumale',
    ML: 'Bamako',
    MT: 'Birkirkara',
    MH: 'Marshall Islands', // no edit
    MQ: 'Martinique', // no edit
    MR: 'Nouakchott',
    MU: 'Grand Baie',
    YT: 'Mayotte', // no edit
    MX: 'Tulum',
    MD: 'Tiraspol',
    MC: 'Monaco',
    MN: 'Ulaanbaatar',
    ME: 'Bar',
    MS: 'Montserrat', // no edit
    MA: 'Marrakesh',
    MZ: 'Maputo',
    MM: 'Mandalay',
    NA: 'Walvis Bay',
    NR: 'Nauru', // no edit
    NP: 'Biratnagar',
    NL: 'Bussum',
    NC: 'Noumea',
    NZ: 'Auckland',
    NI: 'Jinotega',
    NE: 'Niger', // no edit
    NG: 'Abuja',
    NU: 'Niue', // no edit
    NF: 'Norfolk Island', // no edit
    KP: 'North Korea', // no edit
    MP: 'Saipan',
    NO: 'Oslo',
    OM: 'Muscat',
    PK: 'Bahawalpur',
    PW: 'Palau', // no edit
    PS: 'Palestine', // no edit
    PA: 'Panama City',
    PG: 'Port Moresby',
    PY: 'Limpio',
    PE: 'Lima',
    PH: 'Cebu',
    PN: 'Pitcairn Islands', // no edit
    PL: 'Augustow',
    PT: 'Lisbon',
    PR: 'Dorado',
    QA: 'Doha',
    RE: 'Saint Pierre',
    RO: 'Arad',
    RU: 'Moscow',
    RW: 'Kigali',
    SH: 'Saint Helena', // no edit
    KN: 'Saint Kitts and Nevis', // noedit
    LC: 'Dennery',
    PM: 'Saint Pierre and Miquelon', // no edit
    VC: 'Saint Vincent and the Grenadines', // no edit
    WS: 'Samoa', // paused here!!!!
    SM: 'San Marino',
    ST: 'São Tomé and Príncipe',
    SA: 'Saudi Arabia',
    SN: 'Senegal',
    RS: 'Serbia',
    SC: 'Seychelles',
    SL: 'Sierra Leone',
    SG: 'Singapore',
    SX: 'Sint Maarten',
    SK: 'Slovakia',
    SI: 'Slovenia',
    SB: 'Solomon Islands',
    SO: 'Somalia',
    ZA: 'South Africa',
    GS: 'South Georgia and the South Sandwich Islands',
    KR: 'South Korea',
    SS: 'South Sudan',
    ES: 'Spain',
    LK: 'Sri Lanka',
    SD: 'Sudan',
    SR: 'Suriname',
    SJ: 'Svalbard and Jan Mayen',
    SZ: 'Eswatini',
    SE: 'Sweden',
    CH: 'Switzerland',
    SY: 'Syria',
    TW: 'Taiwan',
    TJ: 'Tajikistan',
    TZ: 'Tanzania',
    TH: 'Thailand',
    TL: 'Timor-Leste',
    TG: 'Togo',
    TK: 'Tokelau',
    TO: 'Tonga',
    TT: 'Trinidad and Tobago',
    TN: 'Tunisia',
    TR: 'Turkey',
    TM: 'Turkmenistan',
    TC: 'Turks and Caicos Islands',
    TV: 'Tuvalu',
    UG: 'Uganda',
    UA: 'Ukraine',
    AE: 'United Arab Emirates',
    GB: 'United Kingdom',
    US: 'United States',
    UM: 'United States Minor Outlying Islands',
    VI: 'United States Virgin Islands',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VU: 'Vanuatu',
    VA: 'Vatican City',
    VE: 'Venezuela',
    VN: 'Vietnam',
    WF: 'Wallis and Futuna',
    EH: 'Western Sahara',
    YE: 'Yemen',
    ZM: 'Zambia',
    ZW: 'Zimbabwe'
  };