export default {
    AF: 'Kabul',
    AX: 'Mariehamn',
    AL: 'Tirana',
    DZ: 'Algiers',
    AS: 'American Samoa', //not edited
    AD: 'Andorra la Vella',
    AO: 'Luanda',
    AI: 'Anguilla',// not edited
    AQ: 'Antarctica', // not edit
    AG: "St John's",
    AR: 'Buenos Aires',
    AM: 'Yerevan',
    AW: 'Oranjestad',
    AU: 'Sydney',
    AT: 'Vienna',
    AZ: 'Baku',
    BS: 'Nassau',
    BH: 'Manama',
    BD: 'Dhaka',
    BB: 'Bridgetown',
    BY: 'Minsk',
    BE: 'Brussels',
    BZ: 'Belmopan',
    BJ: 'Benin', //not edited
    BM: 'Hamilton',
    BT: 'Thimphu',
    BO: 'La Paz',
    BA: 'Sarajevo',
    BW: 'Gaborone',
    BR: 'Brasilia',
    IO: 'British Indian Ocean Territory', // not edited
    VG: 'Road Town',
    BN: 'Bandar Seri Begawan',
    BG: 'Sofia',
    BF: 'Ouagadougou',
    BI: 'Gitega',
    KH: 'Phnom Penh',
    CM: 'Yaounde',
    CA: 'Ottawa',
    CV: 'Praia',
    BQ: 'Caribbean Netherlands', // not edited
    KY: 'George Town',
    CF: 'Central African Republic', //not edited
    TD: 'Baibokoum',
    CL: 'Santiago',
    CN: 'Beijing',
    CX: 'Christmas Island', //no edit
    CC: 'Cocos Islands', //no edit
    CO: 'Bogota',
    KM: 'Comoros', //no edit
    CG: 'Kinshasa',
    CK: 'Cook Islands', // no edit
    CR: 'San José',
    HR: 'Zagreb',
    CU: 'Havana',
    CW: 'Willemstad',
    CY: 'Nicosia',
    CZ: 'Prague',
    CD: 'Democratic Republic of the Congo', // no edit
    DK: 'Copenhagen',
    DJ: 'Djibouti',
    DM: 'Roseau',
    DO: 'Boca Chica',
    EC: 'Quito',
    EG: 'Cairo',
    SV: 'San Salvador',
    GQ: 'Malabo',
    ER: 'Eritrea', // no edit
    EE: 'Haapsalu',
    ET: 'Addis Ababa',
    FK: 'Falkland Islands', // no edit
    FO: 'Tórshavn',
    FM: 'Federated States of Micronesia', // no edit
    FJ: 'Fiji',
    FI: 'Helsinki',
    FR: 'Paris',
    GF: 'French Guiana', // no edit
    PF: 'Amaru',
    TF: 'French Southern Territories', // no edit
    GA: 'Libreville',
    GM: 'Banjul',
    GE: 'Tbilisi',
    DE: 'Berlin',
    GH: 'Tongo',
    GI: 'Gibraltar',
    GR: 'Athens',
    GL: 'Nuuk',
    GD: 'Sauteurs',
    GP: 'Guadeloupe',
    GU: 'Hagåtña',
    GT: 'Zacapa',
    GN: 'Guinea', // no edit
    GW: 'Gabu',
    GY: 'Georgetown',
    HT: 'Yoro',
    HN: 'Honduras',
    HK: 'Hong Kong',
    HU: 'Budapest',
    IS: 'Iceland',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Iran',
    IQ: 'Iraq',
    IE: 'Ireland',
    IM: 'Isle of Man',
    IL: 'Israel',
    IT: 'Italy',
    CI: 'Ivory Coast',
    JM: 'Jamaica',
    JP: 'Japan',
    JE: 'Jersey',
    JO: 'Jordan',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KI: 'Kiribati',
    XK: 'Kosovo',
    KW: 'Kuwait',
    KG: 'Kyrgyzstan',
    LA: 'Laos',
    LV: 'Latvia',
    LB: 'Lebanon',
    LS: 'Lesotho',
    LR: 'Liberia',
    LY: 'Libya',
    LI: 'Liechtenstein',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MO: 'Macau',
    MK: 'Macedonia',
    MG: 'Madagascar',
    MW: 'Malawi',
    MY: 'Malaysia',
    MV: 'Maldives',
    ML: 'Mali',
    MT: 'Malta',
    MH: 'Marshall Islands',
    MQ: 'Martinique',
    MR: 'Mauritania',
    MU: 'Mauritius',
    YT: 'Mayotte',
    MX: 'Mexico',
    MD: 'Moldova',
    MC: 'Monaco',
    MN: 'Mongolia',
    ME: 'Montenegro',
    MS: 'Montserrat',
    MA: 'Morocco',
    MZ: 'Mozambique',
    MM: 'Myanmar',
    NA: 'Namibia',
    NR: 'Nauru',
    NP: 'Nepal',
    NL: 'Netherlands',
    NC: 'New Caledonia',
    NZ: 'New Zealand',
    NI: 'Nicaragua',
    NE: 'Niger',
    NG: 'Nigeria',
    NU: 'Niue',
    NF: 'Norfolk Island',
    KP: 'North Korea',
    MP: 'Northern Mariana Islands',
    NO: 'Norway',
    OM: 'Oman',
    PK: 'Pakistan',
    PW: 'Palau',
    PS: 'Palestine',
    PA: 'Panama',
    PG: 'Papua New Guinea',
    PY: 'Paraguay',
    PE: 'Peru',
    PH: 'Philippines',
    PN: 'Pitcairn Islands',
    PL: 'Poland',
    PT: 'Portugal',
    PR: 'Puerto Rico',
    QA: 'Qatar',
    RE: 'Reunion',
    RO: 'Romania',
    RU: 'Moscow',
    RW: 'Rwanda',
    SH: 'Saint Helena',
    KN: 'Saint Kitts and Nevis',
    LC: 'Saint Lucia',
    PM: 'Saint Pierre and Miquelon',
    VC: 'Saint Vincent and the Grenadines',
    WS: 'Samoa',
    SM: 'San Marino',
    ST: 'São Tomé and Príncipe',
    SA: 'Saudi Arabia',
    SN: 'Senegal',
    RS: 'Serbia',
    SC: 'Seychelles',
    SL: 'Sierra Leone',
    SG: 'Singapore',
    SX: 'Sint Maarten',
    SK: 'Slovakia',
    SI: 'Slovenia',
    SB: 'Solomon Islands',
    SO: 'Somalia',
    ZA: 'South Africa',
    GS: 'South Georgia and the South Sandwich Islands',
    KR: 'South Korea',
    SS: 'South Sudan',
    ES: 'Spain',
    LK: 'Sri Lanka',
    SD: 'Sudan',
    SR: 'Suriname',
    SJ: 'Svalbard and Jan Mayen',
    SZ: 'Eswatini',
    SE: 'Sweden',
    CH: 'Switzerland',
    SY: 'Syria',
    TW: 'Taiwan',
    TJ: 'Tajikistan',
    TZ: 'Tanzania',
    TH: 'Thailand',
    TL: 'Timor-Leste',
    TG: 'Togo',
    TK: 'Tokelau',
    TO: 'Tonga',
    TT: 'Trinidad and Tobago',
    TN: 'Tunisia',
    TR: 'Turkey',
    TM: 'Turkmenistan',
    TC: 'Turks and Caicos Islands',
    TV: 'Tuvalu',
    UG: 'Uganda',
    UA: 'Ukraine',
    AE: 'United Arab Emirates',
    GB: 'United Kingdom',
    US: 'United States',
    UM: 'United States Minor Outlying Islands',
    VI: 'United States Virgin Islands',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VU: 'Vanuatu',
    VA: 'Vatican City',
    VE: 'Venezuela',
    VN: 'Vietnam',
    WF: 'Wallis and Futuna',
    EH: 'Western Sahara',
    YE: 'Yemen',
    ZM: 'Zambia',
    ZW: 'Zimbabwe'
  };