export default {
    AF: 'Kabul',
    AX: 'Mariehamn',
    AL: 'Tirana',
    DZ: 'Algiers',
    AD: 'Andorra la Vella',
    AO: 'Luanda',
    AG: "St John's",
    AR: 'Buenos Aires',
    AM: 'Yerevan',
    AW: 'Oranjestad',
    AU: 'Sydney',
    AT: 'Vienna',
    AZ: 'Baku',
    BS: 'Nassau',
    BH: 'Manama',
    BD: 'Dhaka',
    BB: 'Bridgetown',
    BY: 'Minsk',
    BE: 'Brussels',
    BZ: 'Belmopan',
    BM: 'Hamilton',
    BT: 'Thimphu',
    BO: 'La Paz',
    BA: 'Sarajevo',
    BW: 'Gaborone',
    BR: 'Rio de Janeiro',
    VG: 'Road Town',
    BN: 'Bandar Seri Begawan',
    BG: 'Sofia',
    BF: 'Ouagadougou',
    BI: 'Gitega',
    KH: 'Phnom Penh',
    CM: 'Yaounde',
    CA: 'Calgary',
    CV: 'Praia',
    KY: 'George Town',
    TD: 'Baibokoum',
    CL: 'Santiago',
    CN: 'Beijing',
    CO: 'Bogota',
    CG: 'Kinshasa',
    CR: 'San José',
    HR: 'Zagreb',
    CU: 'Havana',
    CW: 'Willemstad',
    CY: 'Nicosia',
    CZ: 'Prague',
    CD: 'Brazzaville',
    DK: 'Copenhagen',
    DJ: 'Djibouti',
    DM: 'Roseau',
    DO: 'Boca Chica',
    EC: 'Quito',
    EG: 'Cairo',
    SV: 'San Salvador',
    GQ: 'Malabo',
    EE: 'Tartu',
    ET: 'Addis Ababa',
    FO: 'Tórshavn',
    FJ: 'Fiji',
    FI: 'Helsinki',
    FR: 'Paris',
    PF: 'Amaru',
    GA: 'Libreville',
    GM: 'Banjul',
    GE: 'Tbilisi',
    DE: 'Berlin',
    GH: 'Tongo',
    GI: 'Gibraltar',
    GR: 'Athens',
    GL: 'Nuuk',
    GD: 'Sauteurs',
    GP: 'Guadeloupe',
    GU: 'Hagåtña',
    GT: 'Zacapa',
    GW: 'Gabu',
    GY: 'Georgetown',
    HT: 'Yoro',
    HN: 'La Paz',
    HK: 'Hong Kong',
    HU: 'Budapest',
    IS: 'Reykjavík',
    IN: 'Goa',
    ID: 'Ubud',
    IR: 'Tehran',
    IQ: 'Nasiriyah',
    IE: 'Dublin',
    IM: 'Ramsey',
    IL: 'Jerusalem',
    IT: 'Rome',
    CI: 'San-Pedro',
    JM: 'Kingston',
    JP: 'Tokyo',
    JE: 'St Helier',
    JO: 'Al-qasr',
    KZ: 'Almaty',
    KE: 'Nairobi',
    KI: 'Kiribati', // no edit
    XK: 'Gjilan',
    KW: 'Rawda',
    KG: 'Kant',
    LA: 'Vientiane',
    LV: 'Jelgava',
    LB: 'Beirut',
    LS: 'Mafeteng',
    LR: 'Ganta',
    LY: 'Benghazi',
    LI: 'Liechtenstein', // no edit
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MO: 'Macao',
    MK: 'Macedonia', // no edit
    MG: 'Antananarivo',
    MW: 'Blantyre',
    MY: 'Kuala Lumpur',
    MV: 'Hulhumale',
    ML: 'Bamako',
    MT: 'Birkirkara',
    MH: 'Marshall Islands', // no edit
    MQ: 'Martinique', // no edit
    MR: 'Nouakchott',
    MU: 'Grand Baie',
    YT: 'Mayotte', // no edit
    MX: 'Mexico City',
    MD: 'Chisinau',
    MC: 'Monaco',
    MN: 'Ulaanbaatar',
    ME: 'Bar',
    MS: 'Montserrat', // no edit
    MA: 'Marrakesh',
    MZ: 'Maputo',
    MM: 'Mandalay',
    NA: 'Walvis Bay',
    NR: 'Nauru', // no edit
    NP: 'Biratnagar',
    NL: 'Bussum',
    NC: 'Noumea',
    NZ: 'Auckland',
    NI: 'Jinotega',
    NE: 'Niger', // no edit
    NG: 'Abuja',
    NU: 'Niue', // no edit
    NF: 'Norfolk Island', // no edit
    KP: 'North Korea', // no edit
    MP: 'Saipan',
    NO: 'Oslo',
    OM: 'Muscat',
    PK: 'Bahawalpur',
    PA: 'Panama City',
    PG: 'Port Moresby',
    PY: 'Asuncion',
    PE: 'Lima',
    PH: 'Cebu',
    PL: 'Wroclaw',
    PT: 'Lisbon',
    PR: 'Dorado',
    QA: 'Doha',
    RE: 'Saint Pierre',
    RO: 'Cluj-Napoca',
    RU: 'Moscow',
    RW: 'Kigali',
    LC: 'Dennery',
    WS: 'Apia', 
    SA: 'Riyadh',
    SN: 'Foundiougne',
    RS: 'Belgrade',
    SC: 'Mahé',
    SG: 'Singapore',
    SX: 'Philipsburg',
    SK: 'Bratislava',
    SI: 'Ljubljana',
    SB: 'Honiara',
    SO: 'Hargeisa',
    ZA: 'Cape Town',
    KR: 'Seoul',
    SS: 'Juba',
    ES: 'Barcelona',
    LK: 'Colombo',
    SD: 'Khartoum',
    SR: 'Friendship',
    SJ: 'Svalbard and Jan Mayen', // no edit
    SZ: 'Eswatini', // no edit
    SE: 'Gothenburg',
    CH: 'Baden',
    SY: 'Syria', // no edit
    TW: 'Taipei',
    TJ: 'Dushanbe',
    TZ: 'Dar es Salaam',
    TH: 'Bangkok',
    TG: 'Lome',
    TO: 'Hihifo',
    TT: 'Chaguanas',
    TN: 'La Marsa',
    TR: 'Ankara',
    TM: 'Ashgabat',
    TC: 'Providenciales',
    UG: 'Gulu',
    UA: 'Kiev',
    AE: 'Abu Dhabi',
    GB: 'London',
    US: 'San Francisco',
    VI: 'Frederiksted', 
    UY: 'Montevideo',
    UZ: 'Tashkent',
    VU: 'Port Vila',
    VE: 'Caracas',
    VN: 'Hanoi',
    YE: 'Aden',
    ZM: 'Kitwe',
    ZW: 'Bulawayo'
  
  };